

// Hämta arbetslöshet för bara de kommunerna
dbQuery.use("arbetsloshet");

let data = await dbQuery('SELECT Region, Arbetsloshet_2022 FROM arbetsloshet')







const kommunTillLan = {
  "Ale": "Västra Götalands län",
  "Alingsås": "Västra Götalands län",
  "Alvesta": "Kronobergs län",
  "Aneby": "Jönköpings län",
  "Arboga": "Västmanlands län",
  "Arjeplog": "Norrbottens län",
  "Arvidsjaur": "Norrbottens län",
  "Arvika": "Värmlands län",
  "Askersund": "Örebro län",
  "Avesta": "Dalarnas län",
  "Bengtsfors": "Västra Götalands län",
  "Berg": "Jämtlands län",
  "Bjurholm": "Västerbottens län",
  "Bjuv": "Skåne län",
  "Boden": "Norrbottens län",
  "Bollebygd": "Västra Götalands län",
  "Bollnäs": "Gävleborgs län",
  "Borgholm": "Kalmar län",
  "Borlänge": "Dalarnas län",
  "Borås": "Västra Götalands län",
  "Botkyrka": "Stockholms län",
  "Boxholm": "Östergötlands län",
  "Bromölla": "Skåne län",
  "Bräcke": "Jämtlands län",
  "Burlöv": "Skåne län",
  "Båstad": "Skåne län",
  "Dals-Ed": "Västra Götalands län",
  "Danderyd": "Stockholms län",
  "Degerfors": "Örebro län",
  "Dorotea": "Västerbottens län",
  "Eda": "Värmlands län",
  "Ekerö": "Stockholms län",
  "Eksjö": "Jönköpings län",
  "Emmaboda": "Kalmar län",
  "Enköping": "Uppsala län",
  "Eskilstuna": "Södermanlands län",
  "Eslöv": "Skåne län",
  "Essunga": "Västra Götalands län",
  "Fagersta": "Västmanlands län",
  "Falkenberg": "Hallands län",
  "Falköping": "Västra Götalands län",
  "Falun": "Dalarnas län",
  "Filipstad": "Värmlands län",
  "Finspång": "Östergötlands län",
  "Flen": "Södermanlands län",
  "Forshaga": "Värmlands län",
  "Färgelanda": "Västra Götalands län",
  "Gagnef": "Dalarnas län",
  "Gislaved": "Jönköpings län",
  "Gnesta": "Södermanlands län",
  "Gnosjö": "Jönköpings län",
  "Gotland": "Gotlands län",
  "Grums": "Värmlands län",
  "Grästorp": "Västra Götalands län",
  "Gullspång": "Västra Götalands län",
  "Gällivare": "Norrbottens län",
  "Gävle": "Gävleborgs län",
  "Göteborg": "Västra Götalands län",
  "Götene": "Västra Götalands län",
  "Habo": "Jönköpings län",
  "Hagfors": "Värmlands län",
  "Hallsberg": "Örebro län",
  "Hallstahammar": "Västmanlands län",
  "Halmstad": "Hallands län",
  "Hammarö": "Värmlands län",
  "Haninge": "Stockholms län",
  "Haparanda": "Norrbottens län",
  "Heby": "Uppsala län",
  "Hedemora": "Dalarnas län",
  "Helsingborg": "Skåne län",
  "Herrljunga": "Västra Götalands län",
  "Hjo": "Västra Götalands län",
  "Hofors": "Gävleborgs län",
  "Huddinge": "Stockholms län",
  "Hudiksvall": "Gävleborgs län",
  "Hultsfred": "Kalmar län",
  "Hylte": "Hallands län",
  "Håbo": "Uppsala län",
  "Hällefors": "Örebro län",
  "Härjedalen": "Jämtlands län",
  "Härnösand": "Västernorrlands län",
  "Härryda": "Västra Götalands län",
  "Hässleholm": "Skåne län",
  "Höganäs": "Skåne län",
  "Högsby": "Kalmar län",
  "Hörby": "Skåne län",
  "Höör": "Skåne län",
  "Jokkmokk": "Norrbottens län",
  "Järfälla": "Stockholms län",
  "Jönköping": "Jönköpings län",
  "Kalix": "Norrbottens län",
  "Kalmar": "Kalmar län",
  "Karlsborg": "Västra Götalands län",
  "Karlshamn": "Blekinge län",
  "Karlskoga": "Örebro län",
  "Karlskrona": "Blekinge län",
  "Karlstad": "Värmlands län",
  "Katrineholm": "Södermanlands län",
  "Kil": "Värmlands län",
  "Kinda": "Östergötlands län",
  "Kiruna": "Norrbottens län",
  "Klippan": "Skåne län",
  "Knivsta": "Uppsala län",
  "Kramfors": "Västernorrlands län",
  "Kristianstad": "Skåne län",
  "Kristinehamn": "Värmlands län",
  "Krokom": "Jämtlands län",
  "Kumla": "Örebro län",
  "Kungsbacka": "Hallands län",
  "Kungsör": "Västmanlands län",
  "Kungälv": "Västra Götalands län",
  "Kävlinge": "Skåne län",
  "Köping": "Västmanlands län",
  "Laholm": "Hallands län",
  "Landskrona": "Skåne län",
  "Laxå": "Örebro län",
  "Lekeberg": "Örebro län",
  "Leksand": "Dalarnas län",
  "Lerum": "Västra Götalands län",
  "Lessebo": "Kronobergs län",
  "Lidingö": "Stockholms län",
  "Lidköping": "Västra Götalands län",
  "Lilla Edet": "Västra Götalands län",
  "Lindesberg": "Örebro län",
  "Linköping": "Östergötlands län",
  "Ljungby": "Kronobergs län",
  "Ljusdal": "Gävleborgs län",
  "Ljusnarsberg": "Örebro län",
  "Lomma": "Skåne län",
  "Ludvika": "Dalarnas län",
  "Luleå": "Norrbottens län",
  "Lund": "Skåne län",
  "Lycksele": "Västerbottens län",
  "Lysekil": "Västra Götalands län",
  "Malmö": "Skåne län",
  "Malung-Sälen": "Dalarnas län",
  "Malå": "Västerbottens län",
  "Mariestad": "Västra Götalands län",
  "Mark": "Västra Götalands län",
  "Markaryd": "Kronobergs län",
  "Mellerud": "Västra Götalands län",
  "Mjölby": "Östergötlands län",
  "Mora": "Dalarnas län",
  "Motala": "Östergötlands län",
  "Mullsjö": "Jönköpings län",
  "Munkedal": "Västra Götalands län",
  "Munkfors": "Värmlands län",
  "Mölndal": "Västra Götalands län",
  "Mönsterås": "Kalmar län",
  "Mörbylånga": "Kalmar län",
  "Nacka": "Stockholms län",
  "Nora": "Örebro län",
  "Norberg": "Västmanlands län",
  "Nordanstig": "Gävleborgs län",
  "Nordmaling": "Västerbottens län",
  "Norrköping": "Östergötlands län",
  "Norrtälje": "Stockholms län",
  "Norsjö": "Västerbottens län",
  "Nybro": "Kalmar län",
  "Nykvarn": "Stockholms län",
  "Nyköping": "Södermanlands län",
  "Nynäshamn": "Stockholms län",
  "Nässjö": "Jönköpings län",
  "Ockelbo": "Gävleborgs län",
  "Olofström": "Blekinge län",
  "Orsa": "Dalarnas län",
  "Orust": "Västra Götalands län",
  "Osby": "Skåne län",
  "Oskarshamn": "Kalmar län",
  "Ovanåker": "Gävleborgs län",
  "Oxelösund": "Södermanlands län",
  "Pajala": "Norrbottens län",
  "Partille": "Västra Götalands län",
  "Perstorp": "Skåne län",
  "Piteå": "Norrbottens län",
  "Ragunda": "Jämtlands län",
  "Robertsfors": "Västerbottens län",
  "Ronneby": "Blekinge län",
  "Rättvik": "Dalarnas län",
  "Sala": "Västmanlands län",
  "Salem": "Stockholms län",
  "Sandviken": "Gävleborgs län",
  "Sigtuna": "Stockholms län",
  "Simrishamn": "Skåne län",
  "Sjöbo": "Skåne län",
  "Skara": "Västra Götalands län",
  "Skellefteå": "Västerbottens län",
  "Skinnskatteberg": "Västmanlands län",
  "Skurup": "Skåne län",
  "Skövde": "Västra Götalands län",
  "Smedjebacken": "Dalarnas län",
  "Sollefteå": "Västernorrlands län",
  "Sollentuna": "Stockholms län",
  "Solna": "Stockholms län",
  "Sorsele": "Västerbottens län",
  "Sotenäs": "Västra Götalands län",
  "Staffanstorp": "Skåne län",
  "Stenungsund": "Västra Götalands län",
  "Stockholm": "Stockholms län",
  "Storfors": "Värmlands län",
  "Storuman": "Västerbottens län",
  "Strängnäs": "Södermanlands län",
  "Strömstad": "Västra Götalands län",
  "Strömsund": "Jämtlands län",
  "Sundbyberg": "Stockholms län",
  "Sundsvall": "Västernorrlands län",
  "Sunne": "Värmlands län",
  "Surahammar": "Västmanlands län",
  "Svalöv": "Skåne län",
  "Svedala": "Skåne län",
  "Svenljunga": "Västra Götalands län",
  "Säffle": "Värmlands län",
  "Säter": "Dalarnas län",
  "Sävsjö": "Jönköpings län",
  "Söderhamn": "Gävleborgs län",
  "Söderköping": "Östergötlands län",
  "Södertälje": "Stockholms län",
  "Sölvesborg": "Blekinge län",
  "Tanum": "Västra Götalands län",
  "Tibro": "Västra Götalands län",
  "Tidaholm": "Västra Götalands län",
  "Tierp": "Uppsala län",
  "Timrå": "Västernorrlands län",
  "Tingsryd": "Kronobergs län",
  "Tjörn": "Västra Götalands län",
  "Tomelilla": "Skåne län",
  "Torsby": "Värmlands län",
  "Torsås": "Kalmar län",
  "Töreboda": "Västra Götalands län",
  "Trelleborg": "Skåne län",
  "Trollhättan": "Västra Götalands län",
  "Trosa": "Södermanlands län",
  "Tyresö": "Stockholms län",
  "Täby": "Stockholms län",
  "Töreboda": "Västra Götalands län",
  "Uddevalla": "Västra Götalands län",
  "Ulricehamn": "Västra Götalands län",
  "Umeå": "Västerbottens län",
  "Upplands Väsby": "Stockholms län",
  "Upplands-Bro": "Stockholms län",
  "Uppsala": "Uppsala län",
  "Uppvidinge": "Kronobergs län",
  "Vadstena": "Östergötlands län",
  "Vaggeryd": "Jönköpings län",
  "Valdemarsvik": "Östergötlands län",
  "Vallentuna": "Stockholms län",
  "Vansbro": "Dalarnas län",
  "Vara": "Västra Götalands län",
  "Varberg": "Hallands län",
  "Vaxholm": "Stockholms län",
  "Vellinge": "Skåne län",
  "Vetlanda": "Jönköpings län",
  "Vilhelmina": "Västerbottens län",
  "Vimmerby": "Kalmar län",
  "Vindeln": "Västerbottens län",
  "Vingåker": "Södermanlands län",
  "Vårgårda": "Västra Götalands län",
  "Vänersborg": "Västra Götalands län",
  "Vännäs": "Västerbottens län",
  "Värmdö": "Stockholms län",
  "Värnamo": "Jönköpings län",
  "Västervik": "Kalmar län",
  "Västerås": "Västmanlands län",
  "Växjö": "Kronobergs län",
  "Ystad": "Skåne län",
  "Åmål": "Västra Götalands län",
  "Ånge": "Västernorrlands län",
  "Åre": "Jämtlands län",
  "Årjäng": "Värmlands län",
  "Åsele": "Västerbottens län",
  "Åstorp": "Skåne län",
  "Åtvidaberg": "Östergötlands län",
  "Älmhult": "Kronobergs län",
  "Älvdalen": "Dalarnas län",
  "Älvkarleby": "Uppsala län",
  "Älvsbyn": "Norrbottens län",
  "Ängelholm": "Skåne län",
  "Öckerö": "Västra Götalands län",
  "Ödeshög": "Östergötlands län",
  "Örebro": "Örebro län",
  "Örkelljunga": "Skåne län",
  "Örnsköldsvik": "Västernorrlands län",
  "Östersund": "Jämtlands län",
  "Österåker": "Stockholms län",
  "Östhammar": "Uppsala län",
  "Östra Göinge": "Skåne län"
};



// Steg 3: Beräkna medelarbetslösheten per län
let arbetsloshetPerLan = {};

data.forEach(row => {
  let region = row.Region;
  let arbetsloshet = row.Arbetsloshet_2022;

  let lan = kommunTillLan[region];
  if (lan) {
    if (!arbetsloshetPerLan[lan]) {
      arbetsloshetPerLan[lan] = { total: 0, count: 0 };
    }

    arbetsloshetPerLan[lan].total += arbetsloshet;
    arbetsloshetPerLan[lan].count += 1;
  }
});

// Steg 4: Beräkna medelvärdet för varje län
let medelArbetsloshetPerLan = [];

for (let lan in arbetsloshetPerLan) {
  let total = arbetsloshetPerLan[lan].total;
  let count = arbetsloshetPerLan[lan].count;
  let medelArbetsloshet = total / count;

  medelArbetsloshetPerLan.push([lan, medelArbetsloshet]);
}

tableFromData({ data: medelArbetsloshetPerLan}) 